const ShellApi = require('../../../../shell-api/');

/** temporal object that is used to access symbols from closures generated by browserify */
_global = {
    ShellInternalState: ShellApi.ShellInternalState,
    Mongo: ShellApi.Mongo,
    Database: ShellApi.Database,
    Collection: ShellApi.Collection,
    Cursor: ShellApi.Cursor,
    AggregationCursor: ShellApi.AggregationCursor,
    InsertOneResult: ShellApi.InsertOneResult,
    InsertManyResult: ShellApi.InsertManyResult,
    DeleteResult: ShellApi.DeleteResult,
    UpdateResult: ShellApi.UpdateResult,
    BulkWriteResult: ShellApi.BulkWriteResult,
    CommandResult: ShellApi.CommandResult
};
