/* auto-generated by NAPI-RS */
/* eslint-disable */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

const bindingPath = join(__dirname, 'smongo-node.node')

if (existsSync(bindingPath)) {
  localFileExisted = true
  try {
    nativeBinding = require(bindingPath)
  } catch (e) {
    loadError = e
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(
    `Failed to load native binding. Looked for: ${bindingPath}`
  )
}

const { ClientSession, Collection, Database, MongoClient } = nativeBinding

module.exports.ClientSession = ClientSession
module.exports.Collection = Collection
module.exports.Database = Database
module.exports.MongoClient = MongoClient
