exec_timeout_secs: 7200

# Variables for common functions.
#
# compile_and_upload_artifact: Runs the exec compile and release process.
variables:
  - &compile_and_upload_artifact
    command: shell.exec
    params:
      working_dir: src
      shell: bash
      script: |
        set -e
        cat <<RELEASE_MONGOSH > ~/release_mongosh.sh
        set -e
        cd $(pwd)
        source .evergreen/.setup_env
        export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
        export EVERGREEN_EXPANSIONS_PATH="$(pwd)/../tmp/expansions.yaml"
        if [ `uname` == Linux ]; then
          mkdir -p tmp
          cp "$(pwd)/../tmp/expansions.yaml" tmp/expansions.yaml
          (cd scripts/docker && docker build -t ubuntu16.04-build -f ubuntu16.04-build.Dockerfile .)
          echo Starting Docker container build
          docker run -e PUPPETEER_SKIP_CHROMIUM_DOWNLOAD \
            -e EVERGREEN_EXPANSIONS_PATH=/tmp/build/tmp/expansions.yaml \
            -e NODE_JS_VERSION \
            -e BUILD_VARIANT \
            --rm -v $PWD:/tmp/build --network host ubuntu16.04-build \
            -c 'cd /tmp/build && npm run evergreen-release package && dist/mongosh --version'
        else
          npm run evergreen-release package
          if [ `uname` == Darwin ]; then
            # Verify signing
            spctl -a -vvv -t install dist/mongosh
          fi
        fi
        RELEASE_MONGOSH

        if [ `uname` == Darwin ]; then
          ssh -v -p 2222 localhost "bash ~/release_mongosh.sh"
        else
          bash ~/release_mongosh.sh
        fi

        source .evergreen/.setup_env
        export MONGOSH_TEST_EXECUTABLE_PATH="$(pwd)/dist/mongosh"
        echo "$MONGOSH_TEST_EXECUTABLE_PATH"
        npm run test-e2e-ci

  - &test_linux_artifact
    command: shell.exec
    params:
      working_dir: src
      shell: bash
      script: |
        set -e
        source .evergreen/.setup_env
        export EVERGREEN_EXPANSIONS_PATH="$(pwd)/../tmp/expansions.yaml"
        node scripts/download-linux-artifact
        dist/mongosh --version
        export MONGOSH_TEST_EXECUTABLE_PATH="$(pwd)/dist/mongosh"
        echo "$MONGOSH_TEST_EXECUTABLE_PATH"
        npm run test-e2e-ci

  - &compile_and_upload_artifact_ps
    command: shell.exec
    params:
      working_dir: src
      shell: powershell
      script: |
        $ErrorActionPreference = "Stop"
        .\.evergreen\SetupEnv
        node --version
        npm --version
        $Env:PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
        $Env:EVERGREEN_EXPANSIONS_PATH = $(Join-Path -Path '..' -ChildPath 'tmp/expansions.yaml' -Resolve)
        npm run evergreen-release package
        $Env:MONGOSH_TEST_EXECUTABLE_PATH = $(Join-Path -Path '.' -ChildPath 'dist/mongosh.exe' -Resolve)
        echo "$Env:MONGOSH_TEST_EXECUTABLE_PATH"
        npm run test-e2e-ci

# Functions are any command that can be run.
# Variables ending with _ps do the same thing as their non-suffixed counterparts
# but use PowerShell instead.
#
# Current functions:
#   checkout - Checks out the project from git.
#   install - Installs Node and all dependencies.
#   check - Performs linter and dependency checks.
#   test - Runs all tests.
#   test_vscode - Clones the vscode extension repository and runs its tests.
#   compile_and_upload_artifact - Compile the release binary and upload it to S3.
#   test_linux_artifact - Test that the built artifact works where we expect it to.
#                         We use this to verify that e.g. the Ubuntu-built release
#                         binary also works on RHEL and Debian.
#   release_publish - Publishes the npm packages and uploads the tarballs.
functions:
  checkout:
    - command: git.get_project
      params:
        directory: src
  install:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          source .evergreen/.install_node
  install_ps:
    - command: shell.exec
      params:
        working_dir: src
        shell: powershell
        script: |
          .\.evergreen\InstallNode
  check:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          source .evergreen/.setup_env
          npm run check-ci
  check_ps:
    - command: shell.exec
      params:
        working_dir: src
        shell: powershell
        script: |
          .\.evergreen\SetupEnv
          npm run check-ci
  test:
    - command: expansions.write
      params:
        file: tmp/expansions.yaml
        redacted: true
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          set -e
          source .evergreen/.setup_env
          export EVERGREEN_EXPANSIONS_PATH="$(pwd)/../tmp/expansions.yaml"
          npm run test-ci
  test_ps:
    - command: expansions.write
      params:
        file: tmp\expansions.yaml
        redacted: true
    - command: shell.exec
      params:
        working_dir: src
        shell: powershell
        script: |
          $ErrorActionPreference = "Stop"
          .\.evergreen\SetupEnv
          $Env:EVERGREEN_EXPANSIONS_PATH = $(Join-Path -Path '..' -ChildPath 'tmp/expansions.yaml' -Resolve)
          npm run test-ci
  test_vscode:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          set -e
          (cd scripts/docker && docker build -t ubuntu18.04-xvfb -f ubuntu18.04-xvfb.Dockerfile .)
          docker run -e PUPPETEER_SKIP_CHROMIUM_DOWNLOAD \
            -e NODE_JS_VERSION \
            -e BUILD_VARIANT \
            --rm -v $PWD:/tmp/build ubuntu18.04-xvfb \
            -c 'cd /tmp/build && ./testing/test-vscode.sh'
  compile_and_upload_artifact:
    - command: expansions.write
      params:
        file: tmp/expansions.yaml
        redacted: true
    - <<: *compile_and_upload_artifact
  compile_and_upload_artifact_ps:
    - command: expansions.write
      params:
        file: tmp\expansions.yaml
        redacted: true
    - <<: *compile_and_upload_artifact_ps
  test_linux_artifact:
    - command: expansions.write
      params:
        file: tmp/expansions.yaml
        redacted: true
    - <<: *test_linux_artifact
  release_publish:
    - command: expansions.write
      params:
        file: tmp/expansions.yaml
        redacted: true
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          set -e
          source .evergreen/.setup_env
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
          export EVERGREEN_EXPANSIONS_PATH="$(pwd)/../tmp/expansions.yaml"
          npm run evergreen-release publish

# Tasks will show up as the individual blocks in the Evergreen UI that can
# pass or fail.
#
# Current tasks:
#   check - Performs linter and dependency checks.
#   test_{version} - Runs all tests, against a specified mongod version.
#   test_vscode - Run the vscode extension integration tests.
#   compile_and_upload_artifact - Compile the release binary and upload it to S3.
#   test_linux_artifact - Test that the built artifact works where we expect it to.
#   release_publish - Publishes the npm packages and uploads the tarballs.
tasks:
  - name: check
    commands:
      - func: checkout
      - func: install
      - func: check
  - name: check_ps
    commands:
      - func: checkout
      - func: install_ps
      - func: check_ps
  - name: test_m40x
    commands:
      - func: checkout
      - func: install
      - func: test
        vars:
          mongosh_server_test_version: "4.0.x"
  - name: test_m42x
    commands:
      - func: checkout
      - func: install
      - func: test
        vars:
          mongosh_server_test_version: "4.2.x"
  - name: test_m44x
    commands:
      - func: checkout
      - func: install
      - func: test
        vars:
          mongosh_server_test_version: "4.4.x"
  - name: test_m40x_ps
    commands:
      - func: checkout
      - func: install_ps
      - func: test_ps
        vars:
          mongosh_server_test_version: "4.0.x"
  - name: test_m42x_ps
    commands:
      - func: checkout
      - func: install_ps
      - func: test_ps
        vars:
          mongosh_server_test_version: "4.2.x"
  - name: test_m44x_ps
    commands:
      - func: checkout
      - func: install_ps
      - func: test_ps
        vars:
          mongosh_server_test_version: "4.4.x"
  - name: test_vscode
    commands:
      - func: checkout
      - func: install
      - func: test_vscode
  - name: compile_and_upload_artifact_macos
    depends_on:
      - name: check
        variant: darwin
      - name: test_m40x
        variant: darwin
      - name: test_m42x
        variant: darwin
      - name: test_m44x
        variant: darwin
    commands:
      - func: checkout
      - func: install
      - func: compile_and_upload_artifact
  - name: compile_and_upload_artifact_linux
    depends_on:
      - name: check
      - name: test_m40x
        variant: linux
      - name: test_m42x
        variant: linux
      - name: test_m44x
        variant: linux
    commands:
      - func: checkout
      - func: install
      - func: compile_and_upload_artifact
  - name: compile_and_upload_artifact_ps
    depends_on:
      - name: check_ps
      - name: test_m40x_ps
      - name: test_m42x_ps
      - name: test_m44x_ps
    commands:
      - func: checkout
      - func: install_ps
      - func: compile_and_upload_artifact_ps
  - name: test_linux_artifact
    depends_on:
      - name: compile_and_upload_artifact_linux
        variant: linux
    commands:
      - func: checkout
      - func: install
      - func: test_linux_artifact
  - name: release_publish
    depends_on:
      - name: compile_and_upload_artifact_ps
        variant: win32
      - name: compile_and_upload_artifact_linux
        variant: linux
      - name: test_linux_artifact
        variant: rhel_real
      - name: test_linux_artifact
        variant: debian_real
      - name: compile_and_upload_artifact_macos
        variant: darwin_codesign
      - name: test_vscode
        variant: linux
    commands:
      - func: checkout
      - func: install
      - func: release_publish

# Need to run builds for every possible build variant.
buildvariants:
  - name: darwin_codesign
    display_name: "MacOS Mojave (codesign)"
    run_on: macos-1014-codesign
    tasks:
      - name: compile_and_upload_artifact_macos
  - name: darwin
    display_name: "MacOS Mojave"
    run_on: macos-1014
    tasks:
      - name: check
      - name: test_m40x
      - name: test_m42x
      - name: test_m44x
  - name: linux
    display_name: "Ubuntu 18.04"
    run_on: ubuntu1804-test
    tasks:
      - name: check
      - name: test_m40x
      - name: test_m42x
      - name: test_m44x
      - name: test_vscode
      - name: compile_and_upload_artifact_linux
  - name: rhel
    display_name: "Ubuntu 18.04 (rpm target)"
    run_on: ubuntu1804-test
    tasks:
      - name: check
      - name: compile_and_upload_artifact_linux
  - name: debian
    display_name: "Ununtu 18.04 (deb target)"
    run_on: ubuntu1804-test
    tasks:
      - name: check
      - name: compile_and_upload_artifact_linux
  - name: rhel_real
    display_name: "RHEL 8.0"
    run_on: rhel80-large
    tasks:
      - name: test_linux_artifact
  - name: debian_real
    display_name: "Debian 10"
    run_on: debian10-large
    tasks:
      - name: test_linux_artifact
  - name: win32
    display_name: "Windows VS 2019 PowerShell"
    run_on: windows-64-vs2019-test
    tasks:
      - name: check_ps
      - name: test_m40x_ps
      - name: test_m42x_ps
      - name: test_m44x_ps
      - name: compile_and_upload_artifact_ps
  - name: darwin_release_publish
    display_name: "Publish Release"
    run_on: macos-1014-codesign
    tasks:
      - name: release_publish
