# https://github.com/evergreen-ci/evergreen/blob/main/docs/Project-Configuration/Parameterized-Builds.md#project-config
parameters:
  - key: mongodb_driver_version_override
    value: nightly
  - key: node_js_version
    value: 24.11.1
include:
  - filename: .evergreen.yml
