# Functions are any command that can be run.
functions:
  checkout:
    - command: git.get_project
      params:
        directory: src
  install_nvm:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  install_node:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          nvm install 12.4.0
          nvm alias default 12.4.0
  install_npm:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install -g npm@latest
  install_lerna:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install -g lerna
  bootstrap:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install
          npm run bootstrap
  check:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm run check
  test:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm test
  build:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm run compile-exec
  publish:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          echo "################# Publish artifacts to S3, NPM and Github ################"
# Tasks will show up as the individual blocks in the Evergreen UI that can
# pass or fail.
tasks:
  - name: checkout
    commands:
      - func: checkout
  - name: install_nvm
    depends_on: 
      - name: checkout
    commands:
      - func: install_nvm
  - name: install_node
    depends_on:
      - name: install_nvm
    commands:
      - func: install_node
  - name: install_npm
    depends_on: 
      - name: install_node
    commands:
      - func: install_npm
  - name: install_lerna
    depends_on:
      - name: install_npm
    commands:
      - func: install_lerna
  - name: bootstrap
    depends_on: 
      - name: install_lerna
    commands:
      - func: bootstrap
  - name: check
    depends_on: 
      - name: bootstrap
    commands:
      - func: check
  - name: test
    depends_on: 
      - name: check
    commands:
      - func: test
  - name: build
    depends_on:
      - name: test
    commands:
      - func: build
  - name: publish
    depends_on:
      - name: build
    commands:
      - func: publish
# Need to run builds for every possible build variant.
# TODO: Durran: BUILD-10374 - Need OSX Catalina Signing Machine
buildvariants:
  - name: macos
    display_name: "MacOS Mohave"
    run_on: osx-1014
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: ubuntu
    display_name: "Ubuntu 18.04"
    run_on: ubuntu1804-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: ubuntuppc
    display_name: "Ubuntu 18.04 PPC"
    run_on: ubuntu1804-power8-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: ubuntuz
    display_name: "Ubuntu 18.04 Z Series"
    run_on: ubuntu1804-zseries-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: rhel7
    display_name: "RHEL 7.6"
    run_on: rhel76-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: rhelppc
    display_name: "RHEL 7.1 PPC"
    run_on: rhel71-power8-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
  - name: rhelz
    display_name: "RHEL 7.2 Z Series"
    run_on: rhel72-zseries-test
    tasks:
      - name: install_nvm
      - name: install_node
      - name: install_npm
      - name: install_lerna
      - name: bootstrap
      - name: check
      - name: test
      - name: build
      - name: publish
