sudo: required
dist: trusty
language: node_js
node_js:
  - 10.2.1
env:
  matrix:
    - MONGODB_VERSION=4.0.x MONGODB_TOPOLOGY=standalone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libsecret-1-dev
      - gnome-keyring
      - python-gnomekeyring
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run ci
cache:
  directories:
    - $HOME/.electron
