class:
    <<: *__defaultClass
    __constructorArgs:
        - _mapper
        - _name
    __stringRep:
        - this._name
    __hasAsyncChild: true
    runCommand:
        <<: *__defaultMethod
        returnsPromise: true
    getCollectionNames:
        <<: *__defaultMethod
        returnsPromise: true
    getCollectionInfos:
        <<: *__defaultMethod
        returnsPromise: true
        serverVersions:
            - '3.0.0'
            - *ServerVersions.latest
