class:
    <<: *__defaultClass
    __constructorArgs:
        - _mapper
        - _database
    __stringRep:
        - this._database
    help: 'shell-api.database.description'
    runCommand:
        <<: *__defaultMethod
        help: 'shell-api.database.help.run-command'
