class:
    <<: *__defaultClass
    __constructorArgs:
        - _mapper
        - _name
    __stringRep:
        - this._name
    __hasAsyncChild: true
    help:
        help: 'shell-api.database.description'
        docs: 'shell-api.database.link'
        attr:
            - name: runCommand
              description: 'shell-api.database.help.run-command'
            - name: getCollectionNames
              description: 'shell-api.collection.help.get-collection-names.description'
            - name: getCollectionInfos
              description: 'shell-api.collection.help.get-collection-infos.description'
    runCommand:
        <<: *__defaultMethod
        help:
            help: 'shell-api.database.help.run-command.example'
            docs: 'shell-api.database.help.run-command.link'
            attr:
              - description: 'shell-api.database.help.run-command.description'
    getCollectionNames:
        <<: *__defaultMethod
        returnsPromise: true
        serverVersions:
            - *ServerVersions.earliest
            - *ServerVersions.latest
        help:
            help: 'shell-api.database.help.get-collection-names.example'
            docs: 'shell-api.database.help.get-collection-names.link'
            attr:
              - description: 'shell-api.database.help.get-collection-names.description'
    getCollectionInfos:
        <<: *__defaultMethod
        returnsPromise: true
        serverVersions:
            - '3.0.0'
            - *ServerVersions.latest
        help:
            help: 'shell-api.database.help.get-collection-infos.example'
            docs: 'shell-api.database.help.get-collection-infos.link'
            attr:
              - description: 'shell-api.database.help.get-collection-infos.description'
