class:
    <<: *__defaultClass
    __methods:
        wrappee: '_mapper'
        firstArg: 'this'
        wrappeePrefix: 'database_'
    __constructorArgs:
        - _mapper
        - _name
    __stringRep:
        - this._name
    __hasAsyncChild: true
    getCollectionNames:
        <<: *__defaultMethod
        returnsPromise: true
    getCollectionInfos:
        <<: *__defaultMethod
        returnsPromise: true
        serverVersions:
            - '3.0.0'
            - *ServerVersions.latest
    runCommand:
        <<: *__defaultMethod
        returnsPromise: true
    adminCommand:
        <<: *__defaultMethod
        serverVersions:
            - '3.4.0'
            - *ServerVersions.latest
        returnsPromise: true
    aggregate:
        <<: *__defaultMethod
        returnsPromise: true
        returnType: 'AggregationCursor'
    getSiblingDB:
        <<: *__defaultMethod
        returnType: 'Database'
    getCollection:
        <<: *__defaultMethod
        returnsPromise: true
    # dropDatabase:
    #     <<: *__defaultMethod
    #     returnsPromise: true
