__constructorArgs:
    - mapper
    - database
__stringRep:
    - database
help:
    <<: *__defaultAttr
    __value: The database class.
runCommand:
    <<: *__defaultMethod
    help: |-
        Runs an arbitrary command on the database.
