class:
    <<: *__defaultClass
    __constructorArgs:
        - _mapper
        - _database
    __stringRep:
        - this._database
    __hasAsyncChild: true
    help:
        help: 'shell-api.database.description'
        docs: 'https://docs.mongodb.com/manual/reference/method/js-database/'
        attr:
            - name: runCommand
              description: 'shell-api.database.help.run-command'
    runCommand:
        <<: *__defaultMethod
        help:
            help: 'shell-api.database.help.run-command'
