export const SERVER_VERSION_EARLIEST = '0.0.0';
export const SERVER_VERSION_LATEST = '4.4.0';
export const ANY_SERVER_VERSION = [
  SERVER_VERSION_EARLIEST,
  SERVER_VERSION_LATEST
];

export const TOPOLOGY_REPL_SET = 0;
export const TOPOLOGY_STANDALONE = 1;
export const TOPOLOGY_SHARD = 2;
export const ANY_TOPOLOGY = [
  TOPOLOGY_REPL_SET,
  TOPOLOGY_STANDALONE,
  TOPOLOGY_SHARD
];
